<!-- Errors -->
<?php if ($errors): ?>
    <ul class="errorList">
        <?php foreach ($errors as $err): ?>
            <li><?= $err ?></li>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<!-- Errors -->

<div class="container">
    <?php foreach ($data as $post): ?>
        <div class="blog_card">
            <div class="blog_card_header">
                <img src="<?= $post['image'] ?>" alt="image-<?= $post['id'] ?>">
                <div className="blog_card_author">
                    <span>Author : </span>
                    <span><?= $post['author'] ?></span>
                    <br />
                    <span>Created : </span>
                    <span><?= $post['created_at'] ?></span>
                </div>
            </div>
            <div class="blog_card_content">
                <div class="blog_card_title"><?= $post['name'] ?></div>
                <div class="blog_card_body">
                    <?= $post['about'] ?>
                </div>
                <div class="blog_card_readmore">
                    <a href="/<?= $scMetaLanguage ?>/article/<?= $post['slug'] ?>">....read more.</a>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>